Update loongarch architecture processor information
loongarch64/hardinfo pull request #2
Opened 2023-02-13 03:05 UTC by zhuyaliang

更新 cpuinfo 格式，并增加新的信息

2023-02-13 06:31 UTC, yetist approved these changes
LGTM

2023-02-14 08:18 UTC, zhuyaliang commented
@loongarch64/dev-team

2023-02-14 08:31 UTC, xen0n requested changes
因为是不兼容变更，所以你需要在 commit message 附带链接说明之前是基于哪一版代码写的（或者说是基于几几年几月的代码行为写的），然后现在冻结了的 cpuinfo 格式是 https://git.kernel.org/torvalds/c/7153c3cbb5b9b99755659b97861fd4fc909ed86f （短链是[这个用法](https://korg.docs.kernel.org/git-url-shorteners.html)），不会改了

然后你的 Git 作者信息也是错的，邮箱地址里不应该有俩 `@` 符号。建议也改一下。

2023-02-14 08:31 UTC, xen0n commented on includes/loongarch64/processor-platform.h
> +    gchar *family;
不用非得把这边字段顺序调成和展示格式一样吧？

2023-02-14 08:32 UTC, xen0n commented
阻止合并是因为邮箱格式错误，不是别的原因。

2023-02-14 09:25 UTC, zhuyaliang commented
@xen0n 谢谢提醒，一直没有发现邮箱问题，目前已经更正。因为第一次提交作者不是我，所以没有在commit 中写的太详细，只加入了目前最稳定的cpuinfo 的链接

2023-02-14 09:33 UTC, xen0n approved these changes
可以接受了

2023-02-14 09:34 UTC, xen0n commented
> 因为第一次提交作者不是我，所以没有在commit 中写的太详细，只加入了目前最稳定的cpuinfo 的链接

这个没关系吧？为啥一开始提交的人不是你，你这次就不写详细，没搞明白。。

2023-02-14 09:42 UTC, zhuyaliang commented
> > 因为第一次提交作者不是我，所以没有在commit 中写的太详细，只加入了目前最稳定的cpuinfo 的链接
> 
> 这个没关系吧？为啥一开始提交的人不是你，你这次就不写详细，没搞明白。。

平时不太关注内核变更，我也不太清楚第一作者是基于那个版本内核写的，怕出错所以就没加😅

2023-02-14 09:59 UTC, xen0n commented
> > > 因为第一次提交作者不是我，所以没有在commit 中写的太详细，只加入了目前最稳定的cpuinfo 的链接
> > 
> > 
> > 这个没关系吧？为啥一开始提交的人不是你，你这次就不写详细，没搞明白。。
> 
> 平时不太关注内核变更，我也不太清楚第一作者是基于那个版本内核写的，怕出错所以就没加😅

那就提一嘴 之前的适配是基于上游正式合并之前的 Linux 行为进行的 即可，一句不提有点突兀

2023-02-16 01:10 UTC, zhuyaliang commented
> 之前的适配是基于上游正式合并之前的 Linux 行为进行的

打算加入这一句，我的英文水平不是太好
The adaptation code cpuinfo submitted by 56e590d has not officially entered the Linux upstream

2023-02-16 01:31 UTC, xen0n commented
> > 之前的适配是基于上游正式合并之前的 Linux 行为进行的
> 
> 打算加入这一句，我的英文水平不是太好
> The adaptation code cpuinfo submitted by 56e590d has not officially entered the Linux upstream

确实不太好，下次试试机翻 ;-)

我自己翻一版：The previous LoongArch support added in commit xxxx was based on the kernel behavior before the official upstream merge.

2023-02-16 02:53 UTC, cnmushiba commented on includes/loongarch64/processor-platform.h
> +    gchar *family;
没有多占内存就行，这儿问题不大。

2023-02-16 02:53 UTC, cnmushiba approved these changes
没什么问题。

2023-02-16 02:54 UTC, xen0n commented on includes/loongarch64/processor-platform.h
> +    gchar *family;
可以接受

2023-02-16 11:24 UTC, merged